---
title: "Replication of Study \"How Quick Decisions Illuminate Moral Character\" by Clayton R. Critcher, Yoel Inbar and David A. Pizarro (2013, Psychological Science)"
author: "Luna Bellitto (lbellitto@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction
My research interest is in international affairs, specifically I am interested in understanding political dynamics. Recently, I have been trying to understand the relationship between politics and social polarization, leading to ideological (and concrete) conflicts within groups based in the perception of being different from one another. This experiment is compelling to me because it addresses the potential of misleading and misunderstanding that occurs when people categorize each other, resulting in a societal schism. The quick and mislead judgment of members of society, as in this case, can create a separation between “me” and the “other,” the “moral” vs the “immoral” ones. However, recognizing these misinterpretations is of primary importance to understand that this division is more abstract and constructed than real. 

In order to conduct this experiment (Experiment 1), some procedures need to be followed. A sample of around 100 people will be required. Participants will be presented to a scenario involving two people, Justin and Nate, who find a wallet full of cash, and they need to decide if return it to the police or not. In both cases, Justin will make a quick decision while Nate will take a longer time before arriving to his choice. In this case, we will manipulate the speed of the decision. Afterwards, participants will evaluate if Justin and Nate have good/bad principles and standards based on the following criteria: how conflicted each subject was in taking the decision, the reservations that they had, their certainty in the decision taken, and the likelihood of taking the other decision. 

In this experiment, it is important to have a wide sample to ensure randomization. For example, randomization would be essential in minimizing biases regarding inner morality: if a participant is likely to keep the money, they would hardly judge one of the scenarios as immoral. Consequently, randomization and attention to the context’s details will be essential to minimize the impact of confounding variables. Another challenge will be ensuring to correctly replicate the original experiment: the wording of the texts given to participants needs to respect the one of the original, particularly with respect to the emphasis on decision speed.  Indeed, speed in decision taking was the mainstream element that linked to perception of certainty in the previous experiment. 

[Repository](https://github.com/lbellitto/critcher2013) 

[Link to original paper](https://github.com/lbellitto/critcher2013/blob/main/original_paper/Critcher_et_al_2013.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
